version: "3.9"


services:
  java-core:
    build: .
    container_name: java_core
    depends_on:
      - postgres
    ports:
      - "9001:9001"

  go-app:
    build: ../go-app-layer
    container_name: go_gateway
    depends_on:
      - java-core
    ports:
      - "8080:8080"

volumes:
  pgdata:
